FROM python:3.8.2-alpine3.11

ENV FLASK_APP=flaskr
ENV FLASK_ENV=development

COPY . /app

WORKDIR /app

RUN pip install --editable . && flask init-db && pip install --no-cache-dir pytest==5.4.3

CMD ["pytest"]
